### PR TITLE
Allow custom header in python bindings

### PR DESCRIPTION
**Pull request by kilimanjaro**
The generated Python bindings are a lot more opinionated than the C api itself. At moment, I'm adjusting some of the hardcoded behavior; but this might evolve into a slightly more extensible interface for library-specific stuff.

- By default, `find_library` does not know about the active Conda environment on OSX; hence the current use of it it makes it harder to deploy the produced shared library with conda. As a quick fix, I check this explicitly.

### CODE REVIEW

**Comment by karlosz** [comment]
It would be nice if we could specify these parameters via an argument to the generated python bindings function. Then it would be easier to extend for these kinds of things at build-the-shared-library time.

**Comment by kilimanjaro** [comment]
> It would be nice if we could specify these parameters via an argument to the generated python bindings function. Then it would be easier to extend for these kinds of things at build-the-shared-library time.

Yes, I agree. I'm experimenting with this a bit, although I think more broadly we should just make the definitions available for anybody to use (i.e. not necessarily wrap in opaque `python-generator` closure, but rather have `define-library` produce something that can be passed off to a custom python, ruby, whatever generator).

**Comment by karlosz** [comment]
Yes, the way I wrote this really optimized for two goals:
- No pollution of any global namespaces.
- Expediency and minimal amount of code to function
There's not much extensibility, so the guts might/should get reworked to support library authors and custom configurations more.

**Comment by kilimanjaro** [comment]
This is a relatively modest change, and is fine for now (imo). In the longer run we will have our eye on more general mechanisms.

**Pull request merged**
